/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * * `salad` - Салата * `soup` - Супа * `appetizer` - Прдеястие * `main_course` - Основно ястие * `dessert` - Десерт * `beverage` - Напитка
 *
 * Values: salad,soup,appetizer,main_course,dessert,beverage
 */

@JsonClass(generateAdapter = false)
enum class CategoryEnum(val value: kotlin.String) {

    @Json(name = "salad")
    salad("salad"),

    @Json(name = "soup")
    soup("soup"),

    @Json(name = "appetizer")
    appetizer("appetizer"),

    @Json(name = "main_course")
    main_course("main_course"),

    @Json(name = "dessert")
    dessert("dessert"),

    @Json(name = "beverage")
    beverage("beverage");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CategoryEnum) "$data" else null

        /**
         * Returns a valid [CategoryEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CategoryEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

