/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MenuItem

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param menuItem 
 * @param quantity 
 */


data class OrderItem (

    @Json(name = "menu_item")
    val menuItem: MenuItem,

    @Json(name = "quantity")
    val quantity: kotlin.Long? = null

) {


}

