/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param user 
 * @param deliveryAddress 
 * @param items 
 */


data class OrderRequest (

    @Json(name = "user")
    val user: kotlin.Int,

    @Json(name = "delivery_address")
    val deliveryAddress: kotlin.String,

    @Json(name = "items")
    val items: kotlin.collections.List<kotlin.Int>

) {


}

