/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param username Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
 * @param password 
 * @param firstName 
 * @param lastName 
 * @param email 
 */


data class UserRegistration (

    /* Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
    @Json(name = "username")
    val username: kotlin.String,

    @Json(name = "password")
    val password: kotlin.String,

    @Json(name = "first_name")
    val firstName: kotlin.String? = null,

    @Json(name = "last_name")
    val lastName: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null

) {


}

