/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param username 
 * @param firstName 
 * @param lastName 
 * @param message 
 */


data class UserRegistrationResponse (

    @Json(name = "username")
    val username: kotlin.String,

    @Json(name = "first_name")
    val firstName: kotlin.String,

    @Json(name = "last_name")
    val lastName: kotlin.String,

    @Json(name = "message")
    val message: kotlin.String? = "User registered successfully"

) {


}

