/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CategoryEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param description 
 * @param price 
 * @param image 
 * @param category 
 * @param isVegetarian 
 */


data class MenuItem (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "price")
    val price: java.math.BigDecimal,

    @Json(name = "image")
    val image: java.net.URI,

    @Json(name = "category")
    val category: CategoryEnum,

    @Json(name = "is_vegetarian")
    val isVegetarian: kotlin.Boolean? = null

) {


}

