/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Order
import org.openapitools.client.models.StatusEnum

class OrderTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Order
        //val modelInstance = Order()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `orderDate`
        should("test orderDate") {
            // uncomment below to test the property
            //modelInstance.orderDate shouldBe ("TODO")
        }

        // to test the property `deliveryAddress`
        should("test deliveryAddress") {
            // uncomment below to test the property
            //modelInstance.deliveryAddress shouldBe ("TODO")
        }

        // to test the property `user`
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

        // to test the property `items`
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

        // to test the property `totalAmount`
        should("test totalAmount") {
            // uncomment below to test the property
            //modelInstance.totalAmount shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
