/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.ApiApi
import org.openapitools.client.models.MenuItem
import org.openapitools.client.models.Order

class ApiApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ApiApi
        //val apiInstance = ApiApi()

        // to test apiMenuItemsGetAllCategoriesRetrieve
        should("test apiMenuItemsGetAllCategoriesRetrieve") {
            // uncomment below to test apiMenuItemsGetAllCategoriesRetrieve
            //val result : MenuItem = apiInstance.apiMenuItemsGetAllCategoriesRetrieve()
            //result shouldBe ("TODO")
        }

        // to test apiMenuItemsItemsByCategoryRetrieve
        should("test apiMenuItemsItemsByCategoryRetrieve") {
            // uncomment below to test apiMenuItemsItemsByCategoryRetrieve
            //val result : MenuItem = apiInstance.apiMenuItemsItemsByCategoryRetrieve()
            //result shouldBe ("TODO")
        }

        // to test apiMenuItemsList
        should("test apiMenuItemsList") {
            // uncomment below to test apiMenuItemsList
            //val result : kotlin.collections.List<MenuItem> = apiInstance.apiMenuItemsList()
            //result shouldBe ("TODO")
        }

        // to test apiOrdersCreateOrderCreate
        should("test apiOrdersCreateOrderCreate") {
            // uncomment below to test apiOrdersCreateOrderCreate
            //val order : Order =  // Order | 
            //val result : Order = apiInstance.apiOrdersCreateOrderCreate(order)
            //result shouldBe ("TODO")
        }

        // to test apiOrdersLatestOrderRetrieve
        should("test apiOrdersLatestOrderRetrieve") {
            // uncomment below to test apiOrdersLatestOrderRetrieve
            //val result : Order = apiInstance.apiOrdersLatestOrderRetrieve()
            //result shouldBe ("TODO")
        }

        // to test apiOrdersOrdersByUserRetrieve
        should("test apiOrdersOrdersByUserRetrieve") {
            // uncomment below to test apiOrdersOrdersByUserRetrieve
            //val result : Order = apiInstance.apiOrdersOrdersByUserRetrieve()
            //result shouldBe ("TODO")
        }

        // to test apiUsersLoginCreate
        should("test apiUsersLoginCreate") {
            // uncomment below to test apiUsersLoginCreate
            //apiInstance.apiUsersLoginCreate()
        }

        // to test apiUsersRegisterCreate
        should("test apiUsersRegisterCreate") {
            // uncomment below to test apiUsersRegisterCreate
            //apiInstance.apiUsersRegisterCreate()
        }

    }
}
