/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.SchemaApi

class SchemaApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SchemaApi
        //val apiInstance = SchemaApi()

        // to test schemaRetrieve
        should("test schemaRetrieve") {
            // uncomment below to test schemaRetrieve
            //val format : kotlin.String = format_example // kotlin.String | 
            //val lang : kotlin.String = lang_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.schemaRetrieve(format, lang)
            //result shouldBe ("TODO")
        }

    }
}
