# Generated by Django 5.2.1 on 2025-06-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Салата', 'Салата'), ('Супа', 'Супа'), ('Предястие', 'Прдеястие'), ('Основно ястие', 'Основно ястие'), ('Десерт', 'Десерт'), ('Напитка', 'Напитка')], max_length=50),
        ),
    ]
