# Generated by Django 5.2.1 on 2025-06-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Салата', 'Салата'), ('Супа', 'Супа'), ('Предястие', 'Прдеястие'), ('Основно', 'Основно'), ('Десерт', 'Десерт'), ('Напитка', 'Напитка')], max_length=50),
        ),
    ]
